/*
 * generated by Xtext
 */
package org.mcj.karel;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class KarelRuntimeModule extends org.mcj.karel.AbstractKarelRuntimeModule {

}
