/*
 * generated by Xtext
 */
package org.mcj.karel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class KarelUiModule extends org.mcj.karel.ui.AbstractKarelUiModule {
	public KarelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
