/*
* generated by Xtext
*/
package org.mcj.karel.ui.contentassist;

import org.mcj.karel.ui.contentassist.AbstractKarelProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class KarelProposalProvider extends AbstractKarelProposalProvider {

}
